game : game.cpp
	g++ -o game game.cpp `pkg-config allegro-5 allegro_main-5 allegro_font-5 allegro_image-5 allegro_primitives-5 --libs --cflags`

game2 : game2.cpp
	g++ -o game2 game2.cpp `pkg-config allegro-5 allegro_main-5 allegro_font-5 allegro_image-5 allegro_primitives-5 --libs --cflags`

clean :
	rm -f game game2
